name: quick_rescue
description: App móvil de Quick Rescue. Mapa, GPS y botón SOS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1                       # Cliente HTTP simple
  shared_preferences: ^2.2.3         # Persistencia local del token
  geolocator: ^11.0.0                # GPS con permisos
  flutter_map: ^7.0.0                # Mapa con OpenStreetMap (sin API key)
  latlong2: ^0.9.1                   # Tipo LatLng usado por flutter_map
  mobile_scanner: ^5.0.0             # Lector de QR con cámara
  permission_handler: ^11.3.0        # Permisos runtime (cámara, etc.)
  intl: ^0.19.0                      # Formateo de fechas
  url_launcher: ^6.2.6               # Abrir tel:, mailto:, https://

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
