name: quick_rescue
description: App móvil de Quick Rescue. Dashboard del titular, gestión de QR.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0                # GPS para escaneos manuales del titular
  flutter_map: ^7.0.0                # Mapa OSM para vistas del histórico
  latlong2: ^0.9.1
  mobile_scanner: ^5.0.0             # Lector de QR (opcional)
  permission_handler: ^11.3.0
  intl: ^0.19.0
  url_launcher: ^6.2.6               # tel:, mailto:, https://
  qr_flutter: ^4.1.0                 # Renderizado de QR para titular
  share_plus: ^10.0.0                # Compartir QR por WhatsApp/email

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
